# Generated by Django 5.0.6 on 2024-06-06 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='presence',
            old_name='Room',
            new_name='room',
        ),
        migrations.AddField(
            model_name='presence',
            name='justified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='presence',
            name='presence',
            field=models.CharField(max_length=30),
        ),
    ]
