# Generated by Django 5.0.6 on 2024-06-07 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='presence',
            name='room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='administration.room'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='presence',
            name='presence',
            field=models.CharField(max_length=30),
        ),
    ]
