# Generated by Django 5.0.6 on 2024-06-07 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_presence_room_alter_presence_presence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presence',
            name='room',
        ),
    ]
