# Generated by Django 5.0.6 on 2024-06-06 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_rename_room_presence_room_presence_justified_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grade',
            old_name='Subject',
            new_name='subject',
        ),
    ]
