# Generated by Django 4.1 on 2024-06-05 14:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="group",
            name="ues",
        ),
        migrations.RemoveField(
            model_name="group",
            name="users",
        ),
        migrations.RemoveField(
            model_name="groupmembership",
            name="group",
        ),
        migrations.RemoveField(
            model_name="groupmembership",
            name="user",
        ),
        migrations.RemoveField(
            model_name="lesson",
            name="group",
        ),
        migrations.RemoveField(
            model_name="lesson",
            name="subject",
        ),
        migrations.RemoveField(
            model_name="lesson",
            name="teacher",
        ),
        migrations.RemoveField(
            model_name="message",
            name="user",
        ),
        migrations.RemoveField(
            model_name="presence",
            name="room",
        ),
        migrations.RemoveField(
            model_name="presence",
            name="session",
        ),
        migrations.RemoveField(
            model_name="presence",
            name="user",
        ),
        migrations.RemoveField(
            model_name="session",
            name="lesson",
        ),
        migrations.RemoveField(
            model_name="session",
            name="room",
        ),
        migrations.RemoveField(
            model_name="subject",
            name="ues",
        ),
        migrations.DeleteModel(
            name="Grade",
        ),
        migrations.DeleteModel(
            name="Group",
        ),
        migrations.DeleteModel(
            name="GroupMembership",
        ),
        migrations.DeleteModel(
            name="Lesson",
        ),
        migrations.DeleteModel(
            name="Message",
        ),
        migrations.DeleteModel(
            name="Presence",
        ),
        migrations.DeleteModel(
            name="Room",
        ),
        migrations.DeleteModel(
            name="Session",
        ),
        migrations.DeleteModel(
            name="Subject",
        ),
        migrations.DeleteModel(
            name="UE",
        ),
    ]
