# Generated by Django 4.1 on 2024-06-05 17:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_presence_presence"),
    ]

    operations = [
        migrations.AddField(
            model_name="presence",
            name="justified",
            field=models.BooleanField(default=False),
        ),
    ]
